In [7]:
import sqlite3

conn = sqlite3.connect("firewall.db")
cursor = conn.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS threats (
    src_ip TEXT,
    total INTEGER,
    unique_ports INTEGER,
    blocked INTEGER,
    blocked_ratio REAL,
    anomaly INTEGER
)""")
conn.commit()                       
conn.close()

In [8]:
import sqlite3
conn = sqlite3.connect("firewall.db")
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print(cursor.fetchall())

conn.close()

[('threats',)]

In [9]:
import sqlite3
from firewall_analyser import FirewallAnalyser

analyzer = FirewallAnalyser("firewall_big.log")
analyzer.run()
analyzer.save_to_db()

In [10]:
import pandas as pd
import sqlite3
conn = sqlite3.connect("firewall.db")

df = pd.read_sql("SELECT * FROM threats", conn)
conn.close()
df

           src_ip  total  unique_ports  blocked  blocked_ratio  anomaly
0  185.220.101.33     25             1       25            1.0       -1
1    203.0.113.45     45             1       45            1.0       -1
2  45.155.205.211     15            15       15            1.0       -1

In [ ]:
import time
from firewall_analyser import FirewallAnalyser
import pandas as pd

analyzer = FirewallAnalyser("firewall_big.log")
analyzer.stream()

In [12]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("firewall.db")
df = pd.read_sql("SELECT * FROM threats", conn)
conn.close()
df

           src_ip  total  unique_ports  blocked  blocked_ratio  anomaly
0  185.220.101.33     25             1       25            1.0       -1
1    203.0.113.45     45             1       45            1.0       -1
2  45.155.205.211     15            15       15            1.0       -1